module.exports = [
  ':tada: initial commit',
  ':bookmark: version tag',
  ':sparkles: new feature',
  ':package: refactoring',
  ':pig: dirty hack',
  ':books: documentation',
  ':wrench: tooling',
  ':shirt: lint',
  ':racehorse: performance',
  ':lipstick: cosmetic',
  ':rotating_light: test',
  ':art: visual/CSS',
  ':poop: deprecation',
  ':construction: work in progress',
  ':rocket: deploy',
  ':cherry_blossom: clean',
  ':rainbow: big clean',
  ':zap: speed'
]
